prog_char texto0[] PROGMEM = "";        // tabela_textos[0]
prog_char texto1[] PROGMEM = "MENU 1";  // tabela_textos[1]
prog_char texto2[] PROGMEM = "MENU 2";  // tabela_textos[2]
prog_char texto3[] PROGMEM = "TIME DATE"; // tabela_textos[3]
prog_char texto4[] PROGMEM = "LED TESTING"; // tabela_textos[4]
prog_char texto5[] PROGMEM = "PARAM. CONTROL."; // tabela_textos[5]
prog_char texto6[] PROGMEM = ""; // tabela_textos[6]
prog_char texto7[] PROGMEM = "ADJUST LED VALUES"; // tabela_textos[7]
prog_char texto8[] PROGMEM = "TPA AUTOMATIC"; // tabela_textos[8] // Troca Parcial de Água automática.
prog_char texto9[] PROGMEM = "DOSING PUMPS"; // tabela_textos[9]
prog_char texto10[] PROGMEM = "WAVEMAKER"; // tabela_textos[10]
prog_char texto11[] PROGMEM = "HOME"; // tabela_textos[11]
prog_char texto12[] PROGMEM = "CHANGE TIME & DATE"; // tabela_textos[12]
prog_char texto13[] PROGMEM = "SAVE"; // tabela_textos[13]
prog_char texto14[] PROGMEM = "HOUR:"; // tabela_textos[14]
prog_char texto15[] PROGMEM = "DATE:"; // tabela_textos[15]
prog_char texto16[] PROGMEM = "TEST VARIATIONS IN BRIGHTNESS"; // tabela_textos[16]
prog_char texto17[] PROGMEM = "START"; // tabela_textos[17]
prog_char texto18[] PROGMEM = "TEST"; // tabela_textos[18]
prog_char texto19[] PROGMEM = "BRIGHTNESS DIMMING TEST"; // tabela_textos[19]
prog_char texto20[] PROGMEM = "STOP"; // tabela_textos[20]
prog_char texto21[] PROGMEM = "TEST IN PROGRESS"; // tabela_textos[21]
prog_char texto22[] PROGMEM = "TIME:"; // tabela_textos[22]
prog_char texto23[] PROGMEM = "POWER OUTPUT (0-255):"; // tabela_textos[23]
prog_char texto24[] PROGMEM = "WATER TEMPERATURE CONTROL"; // tabela_textos[24]
prog_char texto25[] PROGMEM = "TEMPERATURE GRAPH"; // tabela_textos[25]
prog_char texto26[] PROGMEM = "ORP GRAPH"; // tabela_textos[26]
prog_char texto27[] PROGMEM = "PH TANK GRAPH"; // tabela_textos[27]
prog_char texto28[] PROGMEM = "CALCIUM REACTOR PH GRAPH";// tabela_textos[28]
prog_char texto29[] PROGMEM = "DENSITY GRAPH";// tabela_textos[29]
prog_char texto30[] PROGMEM = "CHANGE WHITE LEDS POWER"; // tabela_textos[30]
prog_char texto31[] PROGMEM = "CHANGE BLUE LEDS POWER"; // tabela_textos[31]
prog_char texto32[] PROGMEM = "CONF. DAYS AND SCHEDULE FOR AUTOMATIC TPA";// tabela_textos[32]
prog_char texto33[] PROGMEM = "DOSING PUMPS SETUP";// tabela_textos[33]
prog_char texto34[] PROGMEM = "CHOOSE A GRAPHIC";// tabela_textos[34]
prog_char texto35[] PROGMEM = "WAVEMAKER"; // tabela_textos[35]
prog_char texto36[] PROGMEM = "CHOOSE A PARAMETER"; // tabela_textos[36]
prog_char texto37[] PROGMEM = "PH CONTROL OF CALCIUM REACTOR"; // tabela_textos[37]
prog_char texto38[] PROGMEM = "ORP CONTROL"; // tabela_textos[38]
prog_char texto39[] PROGMEM = "TANK PH CONTROL";// tabela_textos[39]
prog_char texto40[] PROGMEM = "DENSITY CONTROL"; // tabela_textos[40]
prog_char texto41[] PROGMEM = "CHOOSE A DOSING PUMP"; // tabela_textos[41]
prog_char texto42[] PROGMEM = "DOSING PUMP CALIBRATION"; // tabela_textos[42]
prog_char texto43[] PROGMEM = "MANUAL DOSING"; // tabela_textos[43]
prog_char texto44[] PROGMEM = "AUTOMATIC DOSING CONFIG." ;// tabela_textos[44]
prog_char texto45[] PROGMEM = "PERSONALISED DOSING CONFIG."; // tabela_textos[45]
prog_char texto46[] PROGMEM = "PASSWORD"; // tabela_textos[46]
prog_char texto47[] PROGMEM = "PERSONALISED DOSING CONFIG."; // tabela_textos[47]
prog_char texto48[] PROGMEM = "DOSING PUMPS SETUP"; // tabela_textos[48]
prog_char texto49[] PROGMEM = "AUTOMATIC DOSING REVIEW"; // tabela_textos[49]
prog_char texto50[] PROGMEM = "PERSONALISED DOSING REVIEWP"; // tabela_textos[50]
prog_char texto51[] PROGMEM = "DEACTIVATE DOSING PUMP"; // tabela_textos[51]
prog_char texto52[] PROGMEM = "MOON LIGHT  255 = 100 %"; // tabela_textos[52]
prog_char texto53[] PROGMEM = "TIMER SELECT"; // tabela_textos[53]
prog_char texto54[] PROGMEM = "TIMER SET 1"; // tabela_textos[54]
prog_char texto55[] PROGMEM = "TIMER SET 2"; // tabela_textos[55]
prog_char texto56[] PROGMEM = "TIMER SET 3"; // tabela_textos[56]
prog_char texto57[] PROGMEM = "TIMER SET 4"; // tabela_textos[57]
prog_char texto58[] PROGMEM = "TIMER SET 5"; // tabela_textos[58]
prog_char texto59[] PROGMEM = "MONDAY"; // tabela_textos[59]
prog_char texto60[] PROGMEM = "TUESDAY"; // tabela_textos[60]
prog_char texto61[] PROGMEM = "WEDNESDAY"; // tabela_textos[61]
prog_char texto62[] PROGMEM = "THURSDAY"; // tabela_textos[62]
prog_char texto63[] PROGMEM = "FRIDAY"; // tabela_textos[63]
prog_char texto64[] PROGMEM = "SATURDAY"; // tabela_textos[64]
prog_char texto65[] PROGMEM = "SUNDAY"; // tabela_textos[65]
prog_char texto66[] PROGMEM = "BACK"; // tabela_textos[66]
prog_char texto67[] PROGMEM = ""; // tabela_textos[67]
prog_char texto68[] PROGMEM = ""; // tabela_textos[68]
prog_char texto69[] PROGMEM = "";  // tabela_textos[69]
prog_char texto70[] PROGMEM = "S"; // tabela_textos[70] // Segunda; Sexta e Sábado
prog_char texto71[] PROGMEM = "T";// tabela_textos[71]
prog_char texto72[] PROGMEM = "Q"; // tabela_textos[72] // Quarta e Quinta
prog_char texto73[] PROGMEM = "D"; // tabela_textos[73]
prog_char texto74[] PROGMEM = "DESIRED TEMPERATURE:"; // tabela_textos[74]
prog_char texto75[] PROGMEM = "ALLOWABLE VARIATION:"; // tabela_textos[75]
prog_char texto76[] PROGMEM = "CHANGE TO ACTIVATE THE ALARM:"; // tabela_textos[76]
prog_char texto77[] PROGMEM = "POWER OF WHITE LEDS: 255 = 100%"; // tabela_textos[77]
prog_char texto78[] PROGMEM = "BLUE"; // tabela_textos[78]
prog_char texto79[] PROGMEM = "POWER OF BLUE LEDS: 255 = 100%"; // tabela_textos[79]
prog_char texto80[] PROGMEM = "WHITE"; // tabela_textos[80]
prog_char texto81[] PROGMEM = "CHANGE"; // tabela_textos[81]
prog_char texto82[] PROGMEM = "SAVE EEPROM"; // tabela_textos[82]
prog_char texto83[] PROGMEM = "HOUR:"; // tabela_textos[83]
prog_char texto84[] PROGMEM = "MAXIMUM DURATION"; // tabela_textos[84]
prog_char texto85[] PROGMEM = "ON STAGE:"; // tabela_textos[85]
prog_char texto86[] PROGMEM = "FAIL!"; // tabela_textos[86]
prog_char texto87[] PROGMEM = "NORMAL"; // tabela_textos[87]
prog_char texto88[] PROGMEM = "MANUAL"; // tabela_textos[88]
prog_char texto89[] PROGMEM = "AUTOMATIC"; // tabela_textos[89]
prog_char texto90[] PROGMEM = "PERSONALISED"; // tabela_textos[90]
prog_char texto91[] PROGMEM = "SHOW CONFIG."; // tabela_textos[91]
prog_char texto92[] PROGMEM = "DEACTIVATE MODES"; // tabela_textos[92]
prog_char texto93[] PROGMEM = "TEMPERATURE"; // tabela_textos[93]
prog_char texto94[] PROGMEM = "TANK PH"; // tabela_textos[94]
prog_char texto95[] PROGMEM = "REATOR PH"; // tabela_textos[95]
prog_char texto96[] PROGMEM = "ORP"; // tabela_textos[96]
prog_char texto97[] PROGMEM = "DENSITY"; // tabela_textos[97]
prog_char texto98[] PROGMEM = "PROBE CALIBRATION"; // tabela_textos[98]
prog_char texto99[] PROGMEM = "DESIRED PH:"; // tabela_textos[99]
prog_char texto100[] PROGMEM = "DESIRED ORP:"; // tabela_textos[100]
prog_char texto101[] PROGMEM = "DESIRED DENSITY:"; // tabela_textos[101]
prog_char texto102[] PROGMEM = "DOSING PUMP 1"; // tabela_textos[102]
prog_char texto103[] PROGMEM = "DOSING PUMP 2"; // tabela_textos[103]
prog_char texto104[] PROGMEM = "DOSING PUMP 3"; // tabela_textos[104]
prog_char texto105[] PROGMEM = "PUT CONTAINER UNDER THE NOZZLE"; // tabela_textos[105]
prog_char texto106[] PROGMEM = "PRESS START TO BEGIN DOSING."; // tabela_textos[106]
prog_char texto107[] PROGMEM = "AFTER INSERT VALUE OBTAINED"; // tabela_textos[107]
prog_char texto108[] PROGMEM = "ENTER ML IN THE FIELD BELOW."; // tabela_textos[108]
prog_char texto109[] PROGMEM = "FOR BEST RESULTS REPEAT THE TEST"; // tabela_textos[109]
prog_char texto110[] PROGMEM = "TEST A FEW TIMES AND DO MEDIA."; // tabela_textos[110]
prog_char texto111[] PROGMEM = "DOSING PUMP 1 SELECTED"; // tabela_textos[111]
prog_char texto112[] PROGMEM = "DOSING PUMP 2 SELECTED";// tabela_textos[112]
prog_char texto113[] PROGMEM = "DOSING PUMP 3 SELECTED"; // tabela_textos[113]
prog_char texto114[] PROGMEM = "SELECT VOLUME TO BE DOSED"; // tabela_textos[114]
prog_char texto115[] PROGMEM = "ENTER ML IN THE FIELD BELOW"; // tabela_textos[115]
prog_char texto116[] PROGMEM = "PRESS TO START TO BEGIN."; // tabela_textos[116]
prog_char texto117[] PROGMEM = "DOSAGE STARTS IN 10 SECONDS";// tabela_textos[117]
prog_char texto118[] PROGMEM = "INITIAL:"; // tabela_textos[118]
prog_char texto119[] PROGMEM = "FINAL:"; // tabela_textos[119]
prog_char texto120[] PROGMEM = "SELECT"; // tabela_textos[120]
prog_char texto121[] PROGMEM = "VOLUME "; // tabela_textos[121]
prog_char texto122[] PROGMEM = "(ML/DAY):";  // tabela_textos[122]
prog_char texto123[] PROGMEM = "QUANTITY";  // tabela_textos[123]
prog_char texto124[] PROGMEM = "DOSES NR:";  // tabela_textos[124]
prog_char texto125[] PROGMEM = "SELECTED"; // tabela_textos[125]
prog_char texto126[] PROGMEM = "ON"; // tabela_textos[126]
prog_char texto127[] PROGMEM = "OFF"; // tabela_textos[127]
prog_char texto128[] PROGMEM = "NR. OF DOSES:"; // tabela_textos[128]
prog_char texto129[] PROGMEM = "PUMP 1:"; // tabela_textos[129]
prog_char texto130[] PROGMEM = "PUMP 2:"; // tabela_textos[130]
prog_char texto131[] PROGMEM = "PUMP 3:"; // tabela_textos[131]
prog_char texto132[] PROGMEM = ""; // tabela_textos[132]
prog_char texto133[] PROGMEM = "CALIBRATE"; // tabela_textos[133]
prog_char texto134[] PROGMEM = "DEACTIVATE MODES"; // tabela_textos[134]
prog_char texto135[] PROGMEM = "NEXT"; // tabela_textos[135]
prog_char texto136[] PROGMEM = "CLEAR"; // tabela_textos[136]
prog_char texto137[] PROGMEM = "ENTER"; // tabela_textos[137]
prog_char texto138[] PROGMEM = "BACK"; // tabela_textos[138]
prog_char texto139[] PROGMEM = "AUTOMATIC"; // tabela_textos[139]
prog_char texto140[] PROGMEM = "CUSTOM"; // tabela_textos[140]
prog_char texto141[] PROGMEM = "USE THIS"; // tabela_textos[141]
prog_char texto142[] PROGMEM = "FUNCTION"; // tabela_textos[142]
prog_char texto143[] PROGMEM = "ONLY"; // tabela_textos[143]
prog_char texto144[] PROGMEM = "DISABLED"; // tabela_textos[144]
prog_char texto145[] PROGMEM = "MODES"; // tabela_textos[145]
prog_char texto146[] PROGMEM = "DOSAGE."; // tabela_textos[146]
prog_char texto147[] PROGMEM = "ON"; // tabela_textos[147]
prog_char texto148[] PROGMEM = "DEACTIVATED"; // tabela_textos[148]
prog_char texto149[] PROGMEM = "UM DOS MODOS"; // tabela_textos[149]
prog_char texto150[] PROGMEM = "DEOSES"; // tabela_textos[150]
prog_char texto151[] PROGMEM = "IS:"; // tabela_textos[151]
prog_char texto152[] PROGMEM = "DEACTIVATED"; // tabela_textos[152]
prog_char texto153[] PROGMEM = "BOTH MODES"; // tabela_textos[153]
prog_char texto154[] PROGMEM = "THIS OR"; // tabela_textos[154]
prog_char texto155[] PROGMEM = "WILL:"; // tabela_textos[155]
prog_char texto156[] PROGMEM = "ILUMINACAO MINIMA:"; // tabela_textos[156]
prog_char texto157[] PROGMEM = "LUA CHEIA:"; // tabela_textos[157]
prog_char texto158[] PROGMEM = "NEW MOON:"; //  tabela_textos[158]
prog_char texto159[] PROGMEM = "MOON LIGHT"; // tabela_textos[159]
prog_char texto160[] PROGMEM = "TIMERS"; // tabela_textos[160]
prog_char texto161[] PROGMEM = "LIGAR TIMER"; // tabela_textos[161]
prog_char texto162[] PROGMEM = "DESLIGAR TIMER"; // tabela_textos[162]
prog_char texto163[] PROGMEM = "CHANGED!"; // tabela_textos[163]
prog_char texto164[] PROGMEM = "MANUAL MODE SELECTED"; // tabela_textos[164]
prog_char texto165[] PROGMEM = "AUTOMATIC MODE SELECTED"; // tabela_textos[165]
prog_char texto166[] PROGMEM = "INTERVAL "; // tabela_textos[166]
prog_char texto167[] PROGMEM = "WRONG"; // tabela_textos[167]
prog_char texto168[] PROGMEM = "HORA FINAL"; // tabela_textos[168]
prog_char texto169[] PROGMEM = "WRONG!"; // tabela_textos[169]
prog_char texto170[] PROGMEM = "HOUR"; // tabela_textos[170]
prog_char texto171[] PROGMEM = "MODO PERSONALIZADO SELECIONADO"; // tabela_textos[171]
prog_char texto172[] PROGMEM = "MODO CALIBRACAO SELECIONADO";  // tabela_textos[172]
prog_char texto173[] PROGMEM = "NICE!!"; // tabela_textos[173]
prog_char texto174[] PROGMEM = "TRY AGAIN!"; // tabela_textos[174]
prog_char texto175[] PROGMEM = "6 DIGITS MAXIMUM!"; // tabela_textos[175]
prog_char texto176[] PROGMEM = "THE PERIOD BETWEEN START AND FINAL"; // tabela_textos[176]
prog_char texto177[] PROGMEM = "MUST BE AT LEAST 10 MINUTES!"; // tabela_textos[177]
prog_char texto178[] PROGMEM = "END TIME CAN NOT BE LESS"; // tabela_textos[178]
prog_char texto179[] PROGMEM = "TO START!";// tabela_textos[179]
prog_char texto180[] PROGMEM = "MAXIMUM ILLUMINATION:"; // tabela_textos[180]
prog_char texto181[] PROGMEM = "% ILUMINATED"; // tabela_textos[181]
prog_char texto182[] PROGMEM = "LUNAR FASE:"; // tabela_textos[182]
prog_char texto183[] PROGMEM = "HEASINK TEMP:"; // tabela_textos[183]
prog_char texto184[] PROGMEM = "WATER TEMP:"; // tabela_textos[184]
prog_char texto185[] PROGMEM = "TANK PH:";  // tabela_textos[185]
prog_char texto186[] PROGMEM = "REACTOR PH:";  // tabela_textos[186]
prog_char texto187[] PROGMEM = "DENSITY:"; // tabela_textos[187]
prog_char texto188[] PROGMEM = "ORP:"; // tabela_textos[188]
prog_char texto189[] PROGMEM = "CHILLER:"; // tabela_textos[189]
prog_char texto190[] PROGMEM = "HEATER:"; // tabela_textos[190]
prog_char texto191[] PROGMEM = "REATOR:"; // tabela_textos[191]
prog_char texto192[] PROGMEM = "OZONE:"; // tabela_textos[192]
prog_char texto193[] PROGMEM = "REPOSICAO:"; // tabela_textos[193]
prog_char texto194[] PROGMEM = "NIVEL:"; // tabela_textos[194]
prog_char texto195[] PROGMEM = "TPA:"; // tabela_textos[195]
prog_char texto196[] PROGMEM = "LOW!"; // tabela_textos[196]
prog_char texto197[] PROGMEM = "NORMAL"; // tabela_textos[197]
prog_char texto198[] PROGMEM = "Q"; // tabela_textos[198] // Quinta
prog_char texto199[] PROGMEM = "S"; //  tabela_textos[199] // Sexta 
prog_char texto200[] PROGMEM = "S"; // tabela_textos[200] // Sábado
prog_char texto201[] PROGMEM = "LEDS CONFIG.";// tabela_textos[201]
prog_char texto202[] PROGMEM = "LEDS SETUP"; // tabela_textos[202]
prog_char texto203[] PROGMEM = "SELECT A PERIOD"; // tabela_textos[203]

char* tabela_textos[] PROGMEM = 
{
  texto0, texto1, texto2, texto3, texto4, texto5, texto6, texto7,
  texto8, texto9, texto10, texto11, texto12, texto13, texto14, texto15,
  texto16, texto17, texto18, texto19, texto20, texto21, texto22, texto23,
  texto24, texto25, texto26, texto27, texto28, texto29, texto30, texto31,
  texto32, texto33, texto34, texto35, texto36, texto37, texto38, texto39,
  texto40, texto41, texto42, texto43, texto44, texto45, texto46, texto47,
  texto48, texto49, texto50,  texto51, texto52, texto53, texto54, texto55,
  texto56, texto57, texto58, texto59, texto60, texto61, texto62, texto63,
  texto64, texto65, texto66, texto67, texto68, texto69, texto70, texto71,
  texto72, texto73, texto74, texto75, texto76, texto77, texto78, texto79,
  texto80, texto81, texto82, texto83, texto84, texto85, texto86, texto87, 
  texto88, texto89, texto90, texto91, texto92, texto93, texto94, texto95,
  texto96, texto97, texto98, texto99, texto100, texto101, texto102, texto103,
  texto104, texto105, texto106, texto107, texto108, texto109, texto110,
  texto111, texto112, texto113, texto114, texto115, texto116, texto117,
  texto118, texto119, texto120, texto121, texto122, texto123, texto124, 
  texto125, texto126, texto127, texto128, texto129, texto130, texto131,  
  texto132, texto133, texto134, texto135, texto136, texto137, texto138,
  texto139, texto140, texto141, texto142, texto143, texto144, texto145,
  texto146, texto147, texto148, texto149, texto150, texto151, texto152,
  texto153, texto154, texto155, texto156, texto157, texto158, texto159,
  texto160, texto161, texto162, texto163, texto164, texto165, texto166, 
  texto167, texto168, texto169, texto170, texto171, texto172, texto173, 
  texto174, texto175, texto176, texto177, texto178, texto179, texto180,
  texto181, texto182, texto183, texto184, texto185, texto186, texto187,
  texto188, texto189, texto190, texto191, texto192, texto193, texto194, 
  texto195, texto196, texto197, texto198, texto199, texto200, texto201, 
  texto202, texto203   
};

char* tabela_textos_fase[] PROGMEM =
{
"", // tabela_textos_fase[0]
"NEW MOON", // tabela_textos [1]
"CRESCENT MOON", // tabela_textos [2]
"FULL MOON", // tabela_textos [3] 
"WANING MOON" // tabela_textos [4]
};


