char* tabela_textos[] PROGMEM = 
{
"",        // tabela_textos[0]
"MENU 1", // tabela_textos [1]
"MENU 2", // tabela_textos [2]
"TIME DATE", // tabela_textos [3]
"LED TESTING", // tabela_textos [4]
"PARAM. CONTROL", // tabela_textos [5]
"GRAPHICS", // tabela_textos [6]
"ADJUST LED VALUES", // tabela_textos [7]
"TPA AUTOMATIC", // tabela_textos [8] // Change Partial Water automatic.
"DOSING P.", // tabela_textos [9]
"WAVEMAKER", // tabela_textos [10]
"HOME", // tabela_textos [11]
"CHANGE TIME & DATE", // tabela_textos [12]
"SAVE", // tabela_textos [13]
"HOUR", // tabela_textos [14]
"DATE", // tabela_textos [15]
"TEST VARIATIONS IN BRIGHTNESS", // tabela_textos [16]
"START", // tabela_textos [17]
"TEST", // tabela_textos [18]
"BRIGHTNESS DIMMING TEST", // tabela_textos [19]
"STOP", // tabela_textos [20]
"TEST IN PROGRESS", // tabela_textos [21]
"TIME", // tabela_textos [22]
"POWER OUTPUT (0-255):", // tabela_textos [23]
"WATER TEMPERATURE CONTROL", // tabela_textos [24]
"TEMPERATURE GRAPH", // tabela_textos [25]
"ORP GRAPH", // tabela_textos [26]
"PH TANK GRAPH", // tabela_textos [27]
"CALCIUM REACTOR PH GRAPH", // tabela_textos [28]
"DENSITY GRAPH", // tabela_textos [29]
"CHANGE WHITE LEDS POWER", // tabela_textos [30]
"CHANGE BLUE LEDS POWER", // tabela_textos [31]
"CONF. DAYS AND SCHEDULE FOR AUTOMATIC TPA", // tabela_textos [32]
"CONFIGURATION CHANGE OF METERING", // tabela_textos [33]
"CHOOSE A GRAPHIC", // tabela_textos [34]
"WAVEMAKER", // tabela_textos [35]
"CHOOSE A PARAMETER", // tabela_textos [36]
"PH CONTROL OF CALCIUM REACTOR", // tabela_textos [37]
"ORP CONTROL", // tabela_textos [38]
"TANK PH CONTROL", // tabela_textos [39]
"DENSITY CONTROL", // tabela_textos [40]
"CHOOSE A METERING", // tabela_textos [41]
"CALIBRATE METERING", // tabela_textos [42]
"STRENGTH MANUAL", // tabela_textos [43]
"CONFIGURE AUTOMATIC DOSING", // tabela_textos [44]
"STRENGTH CUSTOM SETUP", // tabela_textos [45]
"ENTER PASSWORD", // tabela_textos [46]
"STRENGTH CUSTOM SETUP", // tabela_textos [47]
"CONFIGURATION CHANGE OF METERING", // tabela_textos [48]
"REVISE CONF. AUTOMATIC DOSAGE", // tabela_textos [49]
"REVISE CUSTOM CONF. DOSAGE", // tabela_textos [50]
"DISABLE METERING", // tabela_textos [51]
"NIGHT LIGHT 255 = 100%", // tabela_textos [52]
"SELECT TIMER", // tabela_textos [53]
"TIMER SET 1", // tabela_textos [54]
"TIMER SET 2", // tabela_textos [55]
"TIMER SET 3", // tabela_textos [56]
"TIMER SET 4", // tabela_textos [57]
"TIMER SET 5", // tabela_textos [58]
"MONDAY", // tabela_textos [59]
"TUESDAY", // tabela_textos [60]
"WEDNESDAY", // tabela_textos [61]
"THURSDAY", // tabela_textos [62]
"FRIDAY", // tabela_textos [63]
"SATURDAY", // tabela_textos [64]
"SUNDAY", // tabela_textos [65]
"BACK", // tabela_textos [66]
"NEW MOON", // tabela_textos [67]
"CRESCENT MOON", // tabela_textos [68]
"FULL MOON", // tabela_textos [69]
"M", // tabela_textos [70] // Monday
"T", // tabela_textos [71] // Tuesday
"W", // tabela_textos [72] // Wednesday 
"S", // tabela_textos [73] // Sunday
"TEMPERATURE", // tabela_textos [74]
"ALLOWABLE VARIATION", // tabela_textos [75]
"CHANGE TO ACTIVATE THE ALARM", // tabela_textos [76]
"POWER OF WHITE LEDS: 255 = 100%", // tabela_textos [77]
"BLUE", // tabela_textos [78]
"POWER OF BLUE LEDS: 255 = 100%", // tabela_textos [79]
"WHITE", // tabela_textos [80]
"CHANGE", // tabela_textos [81]
"SAVE EEPROM", // tabela_textos [82]
"TIME", // tabela_textos [83]
"MAXIMUM", // tabela_textos [84]
"ON STAGE:", // tabela_textos [85]
"FAIL!", // Tabela_textos [86]
"NORMAL", // tabela_textos [87]
"MANUAL", // tabela_textos [88]
"AUTOMATIC", // tabela_textos [89]
"CUSTOM", // tabela_textos [90]
"REVIEW CONFIG.", // Tabela_textos [91]
"MODE OFF", // tabela_textos [92]
"TEMPERATURE", // tabela_textos [93]
"TANK PH", // tabela_textos [94]
"REACTOR PH", // tabela_textos [95]
"ORP", // tabela_textos [96]
"DENSITY", // tabela_textos [97]
"PROBE CALIBRATION", // tabela_textos [98]
"DESIRED PH:", // tabela_textos [99]
"DESIRED ORP:", // tabela_textos [100]
"REQUIRED DENSITY", // tabela_textos [101]
"PUMP  1", // tabela_textos [102]
"PUMP  2", // tabela_textos [103]
"PUMP  3", // tabela_textos [104]
"PUT CONTAINER UNDER THE NOZZLE", // tabela_textos [105]
"PRESS START TO BEGIN DOSING", // Tabela_textos [106]
"AFTER INSERT VALUE OBTAINED,", // tabela_textos [107]
"ML IN THE FIELD BELOW.", // Tabela_textos [107]
"FOR BEST RESULTS REPEAT THE TEST", // tabela_textos [109]
"TEST A FEW TIMES AND DO MEDIA.", // Tabela_textos [110]
"PUMP 1 SELECTED", // tabela_textos [111]
"PUMP 2 SELECTED", // tabela_textos [112]
"PUMP 3 SELECTED", // tabela_textos [113]
"SELECT VOLUME TO BE DOSED,", // tabela_textos [114]
"IN THE FIELD BELOW AND ML", // tabela_textos [115]
"PRESS TO START", // Tabela_textos [116]
"DOSAGE STARTS IN 10 SECONDS", // tabela_textos [117]
"INITIAL", // tabela_textos [118]
"FINAL", // tabela_textos [119]
"SELECT", // tabela_textos [120]
"VOLUME", // tabela_textos [121]
"(ML / DAY):", // tabela_textos [122]
"QUANTITY", // tabela_textos [123]
"DOSAGE:", // tabela_textos [124]
"SELECTED", // tabela_textos [125]
"ON", // tabela_textos [126]
"OFF", // tabela_textos [127]
"NUMBER OF DOSES:", // tabela_textos [128]
"PUMP 1:", // tabela_textos [129]
"PUMP 2:", // tabela_textos [130]
"PUMP 3:",// tabela_textos [131]
"WANING MOON", // tabela_textos [132]
"CALIBRATE", // tabela_textos [133]
"MODE OFF", // tabela_textos [134]
"NEXT", // tabela_textos [135]
"CLEAR", // tabela_textos [136]
"ENTER", // tabela_textos [137]
"BACK", // tabela_textos [138]
"AUTOMATIC", // tabela_textos [139]
"CUSTOM", // tabela_textos [140]
"USE THIS", // tabela_textos [141]
"FUNCTION", // tabela_textos [142]
"ONLY", // tabela_textos [143]
"DISABLED", // tabela_textos [144]
"MODES", // tabela_textos [145]
"DOSAGE.", // Tabela_textos [146]
"ON", // tabela_textos [147]
"OFF", // tabela_textos [148]
"ONE OF THE MODE", // tabela_textos [149]
"DOSING", // tabela_textos [150]
"THIS", // tabela_textos [151]
"DISABLED", // tabela_textos [152]
"BOTH WAYS", // tabela_textos [153]
"ARE OR", // tabela_textos [154]
"WILL BE", // tabela_textos [155]
"MINIMUM ILLUMINATION:", // tabela_textos [156]
"MOON", // tabela_textos [157]
"NEW MOON", // tabela_textos [158]
"NIGHT LIGHT", // tabela_textos [159]
"TIMERS", // tabela_textos [160]
"TIMER ON", // tabela_textos [161]
"TIMER OFF", // tabela_textos [162]
"CHANGE!", // Tabela_textos [163]
"MANUAL MODE SELECTED", // tabela_textos [164]
"AUTO MODE SELECTED", // tabela_textos [165]
"WITHDRAWAL", // tabela_textos [166]
"WRONG!", // Tabela_textos [167]
"END TIME", // tabela_textos [168]
"WRONG!", // Tabela_textos [169]
"TIME", // tabela_textos [170]
"CUSTOM MODE SELECTED", // tabela_textos [171]
"CALIBRATION MODE SELECTED", // tabela_textos [172]
"PASSWORD CORRECT", // tabela_textos [173]
"INCORRECT PASSWORD", // tabela_textos [174]
"MAXIMUM 6 DIGITS!", // Tabela_textos [175]
"GAP BETWEEN THE INITIAL AND FINAL", // tabela_textos [176]
"MUST BE AT LEAST 10 MINUTES!", // Tabela_textos [177]
"END TIME CAN NOT BE LESS", // tabela_textos [178]
"THE ORIGINAL", // tabela_textos [179]
"MAXIMUM LIGHTING", // tabela_textos [180]
"LIGHTED%", // tabela_textos [181]
"LUNAR PHASE:", // tabela_textos [182]
"HEATER TEMP.", // tabela_textos [183]
"WATER TEMP.", // tabela_textos [184]
"TANK PH", // tabela_textos [185]
"REACTOR PH", // tabela_textos [186]
"DENSITY", // tabela_textos [187]
"ORP", // tabela_textos [188]
"CHILLER", // tabela_textos [189]
"HEATER", // tabela_textos [190]
"REACTOR", // tabela_textos [191]
"OZONE", // tabela_textos [192]
"ATO", // tabela_textos [193]
"LEVEL", // tabela_textos [194]
"PWC", // tabela_textos [195]
"LOW", // tabela_textos [196]
"NORMAL", // tabela_textos [197]
"T", // tabela_textos[198] // Thursday
"F", //  tabela_textos[199] // Friday
"S", // tabela_textos[200] // Saturday
"CONFIG. LEDS",// tabela_textos[201]
"CONFIGURAR LEDS", // tabela_textos[202]
"SELECIONE UM PERIODO." // tabela_textos[203]
};
